-- KHO XÁC MINH CA LÀM – SUPABASE SETUP
-- Chạy toàn bộ đoạn này trong Supabase SQL Editor.

create table if not exists public.work_shifts (
  id bigint generated by default as identity primary key,
  work_date date not null,
  start_time time not null,
  end_time time not null,
  job text not null default 'Khác',
  rate numeric not null default 20000,
  status text not null default 'Chưa xác minh',
  note text default '',
  before_images jsonb not null default '[]'::jsonb,
  after_images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.work_shifts enable row level security;

-- Prototype dùng chung một dữ liệu. Chỉ dùng policy này nếu bà muốn
-- mọi người có link app đều có thể xem/thêm/sửa/xóa.
drop policy if exists "public read shifts" on public.work_shifts;
drop policy if exists "public insert shifts" on public.work_shifts;
drop policy if exists "public update shifts" on public.work_shifts;
drop policy if exists "public delete shifts" on public.work_shifts;

create policy "public read shifts" on public.work_shifts for select to anon using (true);
create policy "public insert shifts" on public.work_shifts for insert to anon with check (true);
create policy "public update shifts" on public.work_shifts for update to anon using (true) with check (true);
create policy "public delete shifts" on public.work_shifts for delete to anon using (true);
